# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import jeffery_pb2 as jeffery__pb2


class AIGCStub(object):
    """The AIGC service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateText = channel.unary_unary(
                '/aigc.AIGC/CreateText',
                request_serializer=jeffery__pb2.CreateTextRequest.SerializeToString,
                response_deserializer=jeffery__pb2.CreateTextResponse.FromString,
                )


class AIGCServicer(object):
    """The AIGC service definition.
    """

    def CreateText(self, request, context):
        """Sends a text message to the server and receives an answer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIGCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateText': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateText,
                    request_deserializer=jeffery__pb2.CreateTextRequest.FromString,
                    response_serializer=jeffery__pb2.CreateTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aigc.AIGC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIGC(object):
    """The AIGC service definition.
    """

    @staticmethod
    def CreateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aigc.AIGC/CreateText',
            jeffery__pb2.CreateTextRequest.SerializeToString,
            jeffery__pb2.CreateTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
