# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jeffery.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rjeffery.proto\x12\x04\x61igc\"\xa9\x01\n\x11\x43reateTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nrandomness\x18\x02 \x01(\x02\x12/\n\x0btranslation\x18\x03 \x01(\x0b\x32\x18.aigc.TranslationRequestH\x00\x12\x36\n\x0f\x63opy_generation\x18\x04 \x01(\x0b\x32\x1b.aigc.CopyGenerationRequestH\x00\x42\t\n\x07service\"C\n\x12TranslationRequest\x12-\n\tdirection\x18\x01 \x01(\x0e\x32\x1a.aigc.TranslationDirection\":\n\x15\x43opyGenerationRequest\x12!\n\tplatforms\x18\x01 \x03(\x0e\x32\x0e.aigc.Platform\"\xc5\x01\n\x12\x43reateTextResponse\x12\x1b\n\x13translation_answers\x18\x01 \x03(\t\x12T\n\x17\x63opy_generation_answers\x18\x02 \x03(\x0b\x32\x33.aigc.CreateTextResponse.CopyGenerationAnswersEntry\x1a<\n\x1a\x43opyGenerationAnswersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*F\n\x14TranslationDirection\x12\x16\n\x12\x43HINESE_TO_ENGLISH\x10\x00\x12\x16\n\x12\x45NGLISH_TO_CHINESE\x10\x01*>\n\x08Platform\x12\t\n\x05WEIBO\x10\x00\x12\n\n\x06WECHAT\x10\x01\x12\x0f\n\x0bXIAOHONGSHU\x10\x02\x12\n\n\x06\x44OUYIN\x10\x03\x32G\n\x04\x41IGC\x12?\n\nCreateText\x12\x17.aigc.CreateTextRequest\x1a\x18.aigc.CreateTextResponseB\x07Z\x05/aigcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jeffery_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005/aigc'
  _CREATETEXTRESPONSE_COPYGENERATIONANSWERSENTRY._options = None
  _CREATETEXTRESPONSE_COPYGENERATIONANSWERSENTRY._serialized_options = b'8\001'
  _globals['_TRANSLATIONDIRECTION']._serialized_start=524
  _globals['_TRANSLATIONDIRECTION']._serialized_end=594
  _globals['_PLATFORM']._serialized_start=596
  _globals['_PLATFORM']._serialized_end=658
  _globals['_CREATETEXTREQUEST']._serialized_start=24
  _globals['_CREATETEXTREQUEST']._serialized_end=193
  _globals['_TRANSLATIONREQUEST']._serialized_start=195
  _globals['_TRANSLATIONREQUEST']._serialized_end=262
  _globals['_COPYGENERATIONREQUEST']._serialized_start=264
  _globals['_COPYGENERATIONREQUEST']._serialized_end=322
  _globals['_CREATETEXTRESPONSE']._serialized_start=325
  _globals['_CREATETEXTRESPONSE']._serialized_end=522
  _globals['_CREATETEXTRESPONSE_COPYGENERATIONANSWERSENTRY']._serialized_start=462
  _globals['_CREATETEXTRESPONSE_COPYGENERATIONANSWERSENTRY']._serialized_end=522
  _globals['_AIGC']._serialized_start=660
  _globals['_AIGC']._serialized_end=731
# @@protoc_insertion_point(module_scope)
